version: '3'

services:
  web:
    container_name: web
    hostname: web
    image: nginx:${NGINX_VERSION:-alpine}
    depends_on:
      - app
    ports:
            - "${PORT:-8443}:443"
    volumes:
      - ./docker/web/conf.d:/etc/nginx/conf.d
      - ./docker/web/ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
      - staticdata:/app/static
    networks:
      - nginx_network

  app:
    container_name: app
    hostname: app
    image: ${using_image:-app_fastapi_pyspark_conda:latest}
    expose:
      - 8000
      - 4040
    networks:
      - nginx_network
      - db_network
    ports:
      - "${SPARKUI_PORT:-4050}:4040"
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./db/app_sqlite.db:/app/db/app_sqlite.db
      - staticdata:/app/app/static/
    command: "run_app_reload"
    # depends_on:
    #   - db_postgis
    # links:
    #   - db_postgis:db_postgis

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  staticdata:
